### ISSUE TITLE
Ability to Edit Tip List

### ISSUE THREAD

**Issue by duxswhatdux** [xeden3/joplin-plugin-kity-minder#14]
Is it possible to edit the Tip List?
It seems once added, there is no way to remove or edit what is in the list.

- Unless you do not save the map, the added Tip will be removed.
- However, there is no measure to be able to edit the added Tip afterward if if not Saved
- If the Mindmap is saved, there is no option to remove the Tip, it makes sense that Undo will not remove it.
![Kity Add Tip](https://user-images.githubusercontent.com/45373146/208327740-5c59c46c-3364-4ffb-b04b-81669904a433.png)

This is the version of Joplin used
Joplin 2.8.8 (prod, linux)

Client ID: 2061325a7c3647d8aee2cf42c26d8d25
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13

**Comment by hhaishen** [comment]
Yes, I also encountered the same problem as you. Once added, a new minder will appear after clicking edit again, and the previous one cannot be edited.

It seems that the author has not fixed this problem so far, and the latest version still exists

**Comment by xeden3** [comment]
Due to the fact that the Joplin plugin, joplin-plugin-kity-minder, is developed based on the open-source project 

https://github.com/wythe0102/local-kity-minder, utilizing Baidu's mind map component, 

its core interaction logic follows the original component's interaction methods. Therefore, if there's a need to modify the logic, it requires modifying the core of Kity Minder.

However, I also attempted to add and delete Tips. Indeed, during this editing session, it was impossible to delete them. However, when a Tip is saved and there are no other nodes associated with it, it won't be saved in the current record (thus effectively meaning deletion).

Below are screenshots of multiple saves of the same mind map.

First Edit
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/c2a7abe7-8f8e-4a32-b89a-ed83bc2122e9)
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/eb06bd39-ee1a-4bff-9153-25ab29eb76e7)

After Save
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/21be5859-933e-4987-a46e-03a47f5ef365)

Second Edit
un-check Tips
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/c90643cf-67ce-48eb-8f54-8aff91d4e7c7)

After Save
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/cf182c03-5322-48cb-95b8-86037091b67d)

Last Open
No Tips inside
![image](https://github.com/xeden3/joplin-plugin-kity-minder/assets/38025067/8e0eb493-c9cc-4977-bf31-4aa4fee3bd13)
